version: "3.7"
services:
  carbon-budget:
    build:
      context: .
    volumes:
      - ./:/usr/local/app
      - $HOME/.aws:/root/.aws:ro
      - test_tiles_output:/usr/local/tiles
    working_dir: /usr/local/app
    entrypoint: /bin/bash
volumes:
  test_tiles_output: